@startuml
actor Usuario
boundary Controller
boundary Services
boundary Repositories
boundary Entities
database BD
Usuario --> Controller: Consultar
Controller --> Services: GetObject(id)
Services --> Repositories: Get(id)
Repositories --> Entities: Get(id)
Entities --> BD: QueryGet(id)
BD --> Entities: ObjectRetrieved
Entities --> Repositories: ObjectRetrieved
Repositories --> Services: ObjectRetrieved
Services --> Controller: ObjectRetrieved
Controller --> Usuario: ObjetoRecuperado
@enduml